[package]
name = "converter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
image = "0.24.8"
rayon = "1.8.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tobj = "4.0.1"
